implement undecided/undefined
und could stand for undecided or undefined

I get the following error when I run the code as it is now

I think it is strange
because
I don't know why id would ever be the same twice

Fatal error: Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '169840-custom-en' for key 'PRIMARY' in /Users/student/src/csv/drupal_function.php:99 Stack trace: #0 /Users/student/src/csv/drupal_function.php(99): PDOStatement->execute() #1 /Users/student/src/csv/index.php(50): MyCSV::writeToDatabase(Array, Array, Array, Object(PDO), true) #2 {main} thrown in /Users/student/src/csv/drupal_function.php on line 99


Former-commit-id: 23f6379004e90ae075e7f2ea73b1ca85897c5920